name: test

on:
  workflow_dispatch:

jobs:
  Test_Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Requirements
        run: pip install -r requiremets.txt



